artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

  bucket_name: 'your-bucket-name'
  file_name: 'your-file-name.zip'  


data_validation:
  root_dir: artifacts/data_validation
  final_data_dir: artifacts/data_validation



training:
  root_dir: artifacts/training
  trained_model_dir: artifacts/training/model/temporary_model
  yolo_config_file_path: yolo_config/yolo_config.yaml